config/routes.rb
Paperclip4::Application.routes.draw do
  resources :paintings

  resources :galleries

  root :to => 'paintings#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  has_many :paintings
  
  accepts_nested_attributes_for :paintings
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :gallery_id, :name, :image, :remote_image_url, :crop_x, :crop_y,:crop_w, :crop_h
  belongs_to :gallery
  mount_uploader :image, ImageUploader
  
  attr_accessor :crop_x, :crop_y,:crop_w, :crop_h
  after_update :crop_painting
  
  def crop_painting
	image.recreate_versions! if crop_x.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
		format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
		format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
		format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
		format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paintings }
    end
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    @painting = Painting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/new
  # GET /paintings/new.json
  def new
    @painting = Painting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/1/edit
  def edit
    @painting = Painting.find(params[:id])
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(params[:painting])

    respond_to do |format|
      if @painting.save
		if params[:painting][:image].present?
			format.html {render :crop}
		else
			format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
			format.json { render json: @painting, status: :created, location: @painting }
		end
      else
        format.html { render action: "new" }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paintings/1
  # PUT /paintings/1.json
  def update
    @painting = Painting.find(params[:id])

    respond_to do |format|
      if @painting.update_attributes(params[:painting])
		if params[:painting][:image].present?
			format.html {render :crop}
		else
			format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
			format.json { head :no_content }
		end
      else
        format.html { render action: "edit" }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy

    respond_to do |format|
      format.html { redirect_to paintings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.name %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gallery.name %>
</p>

<div id="paintings">
	<% for painting in @gallery.paintings %>
		<div class="painting">
			<%= image_tag painting.image_url(:thumb).to_s %>
			<div class="name"><%= painting.name %></div>
			<div class="actions">
				<%= link_to "edit", edit_painting_path(painting) %> |
				<%= link_to "remove", painting, :confirm =>"are you sure?", :method => :delete %>
			</div>
		</div>
	<% end %>
	<div class="clear"></div>
</div>

<p>
<%= link_to 'Add a painting', new_painting_path(:gallery_id =>@gallery) %> |
<%= link_to 'Remove Gallery', @gallery, :confirm =>"are you sure?", :method => :delete %> |
<%= link_to 'View Galleries', galleries_path %>
</p

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclip4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">CoDressMe</a>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <li>
				<form class="navbar-form">
					<input type="text" class="input-small" placeholder="Email">
					<input type="password" class="input-small" placeholder="Password">
					  
									
					<button class="btn btn-primary" type="submit">
							Connecte-toi
						<%= link_to "", paintings_path %>
					</button>
				
					<button class="btn btn-custom-spin" type="button">
							Facebook-toi
						<%= link_to "", paintings_path %>
					</button>
				</form>
			</li>
          </ul>
        </div>
      </div>
    </div>
</div>


<div class="navbar nav">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">LOGO</a>
        <div class="nav-collapse">
          <ul class="nav ">
            
				<li><a href="#">CATALOGUE</a></li>
				<li><a href="#">MEMBRES</a></li>
				<li><a href="#">FORUM</a></li>
				<li><a href="#">BLOGUE</a></li>
					
				
			
          </ul>
        </div>
      </div>
    </div>
</div>





  <div class="container">
	<h1></h1>

	<div class="row">
		<div class="span9">
			<div class="input-prepend input-append">
				<div class="btn-group">
					<button class="btn dropdown-toggle" data-toggle="dropdown">
					Critères
					<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						<li>Regions</li>
						<li>Modeuses</li>
						<li>Type de vetement</li>
					</ul>
					</div>
				<input class="span4" id="appendedInputButtons" type="text" placeholder="Rechercher membre: par ex, Lola">
				<button class="btn" type="button">Rechercher</button>
				<button class="btn" type="button">Options</button>
			</div>
		</div
		<div class="span3">
			<button class="btn btn-large btn-custom-lighten span3" type="button">+ VENDS ET ECHANGE ICI</button>
		</div
	</div>
  
  
  
  
	
  
  
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
	  <h4></br></h4>
		<div class="hero-unit oli">
			<h4>REJOINS-NOUS AUJOURD'HUI !</h4>
			<h6 class="petittexte">Vends et échange les vêtements, chaussures & accessoires que tu veux renouveler, et puise dans notre catalogue pour redonner du style à ta garde-robe ! Rejoins aussi une communauté férue de mode (mais sans gaspillage) !</h6>
			</br>
			<p>
				<a class="btn btn-primary ">
					Créer un compte
				</a>
			</p>
		</div>
		
        <h2>Nouveautés</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      
	  
		  <h2>Coup de coeur	</h2>
		  <div class="thumbnail span3" >
					<%= link_to image_tag(Painting.first.image_url(:thumb)), "#" %>
						<div class="text" >
							<p><%= Painting.first.name %></p>
							<p><%= Painting.first.gallery.name %></p>
						</div>
				</div>
		  </div>
		  
	 </div>
		  
  </div>
  
  <h1></br></br></br></h1>
  
  
</body>



<footer>

<div class="navbar navbar-bottom navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">CoDressMe</a>
        <div class="nav-collapse">
          <ul class="nav ">
            <li><a href="#">FACEBOOK</a></li>
				<li><a href="#">TWITTER</a></li>
				<li><a href="#">GOOGLE</a></li>
				<li><a href="#">PINTEREST</a></li>
		  </ul>
		  
        </div>
		<div class="nav-collapse">
          <ul class="nav ">
            <li><a href="#">A propos de nous|</a></li>
				<li><a href="#">Contact|</a></li>
				<li><a href="#">Termes et conditions|</a></li>
				<li><a href="#">Politique de confidentialité|</a></li>
		  </ul>
		  
        </div>
      </div>
    </div>
</div>

</footer>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting, :html => {:multipart => true} do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
    
	<div class="field">
    <%= f.label :gallery_id %><br />
     <%= f.collection_select :gallery_id, Gallery.all, :id, :name %>
  </div>
  
  <div class="field">
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :remote_image_url, "ou une image en ligne" %>
	<%= f.text_field :remote_image_url %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
  
   
  
  
<% end %>

app/views/paintings/crop.html.erb
<h1>crop image_avatar</h1>
<%= image_tag @painting.image_url(:large), id: "cropbox" %>

<%= form_for @painting do |f| %>
	<% %w[x y w h].each do |attribute| %>
		<%= f.text_field "crop_#{attribute}" %> </br>
	<% end %>
	<div class="actions">
		<%= f.submit "Crop" %>
	</div>
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<h4>ARTICLES</h4>

<br/>



  <ul class="thumbnails">
	<% @paintings.each do |painting| %>
		<li >
			<!--<%= link_to image_tag(painting.image_url(:thumb)), painting, {:class => "thumbnail"}  %><br>	-->
			
			<div class="thumbnail" >
				<%= link_to image_tag(painting.image_url(:thumb)), painting %>
					<div class="text" >
						<p><%= painting.name %></p>
						<p><%= painting.gallery.name %></p>
					</div>
			</div>
		</li>
		
		
		
		
		
		
		
			
			
	<% end %>
  </ul>


  





<%= link_to 'New Painting', new_painting_path %>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @painting.name %>
</p>

<p>
  <b>Gallery:</b>
  <%= @painting.gallery_id %>
</p>

<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>


<p>image thumb</p>

<!--
<%= image_tag @painting.image_url(:thumb) %><br>
-->

<%= link_to image_tag(@painting.image_url(:thumb)), "#myModal", "data-toggle" => "modal" %>/<br>


<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Modal header</h3>
	</div>
	<div class="modal-body">
		<p>One fine body…</p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary">Save changes</button>
	</div>
</div



<%= link_to 'Edit', edit_painting_path(@painting) %> |
<%= link_to 'Destroy', @painting, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', paintings_path %>